import Foundation
import AppKit

/// 剪贴板时效性监控器 (PasteboardRecencyTracker)
/// 负责跟踪外部应用复制事件，在用户刚复制内容后短时间 (3秒) 内呼出全盘搜索时提供安全合规的自动预填充内容。
public final class PasteboardRecencyTracker {
    public static let shared = PasteboardRecencyTracker()

    private var timer: Timer?
    private var lastChangeCount: Int = NSPasteboard.general.changeCount
    private var lastCopyTime: Date?
    private var lastConsumedChangeCount: Int = -1
    private var ignoredChangeCounts: Set<Int> = []

    /// 主流密码管理工具与保密剪贴板标记类型（命中即绝不自动粘贴，捍卫用户凭据安全）
    private static let sensitivePasteboardTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),        // 1Password, Bitwarden, KeePass
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),    // macOS 系统密码生成器
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),        // 临时私密数据
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),             // 1Password 专属
        NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType") // 第三方剪贴板保护标准
    ]

    private init() {
        // 监听配置变更，动态启停监控
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(handleConfigChanged),
            name: .atoolsAutoPasteOnSummonDidChange,
            object: nil
        )

        // 监听系统休眠与唤醒
        NSWorkspace.shared.notificationCenter.addObserver(
            self,
            selector: #selector(handleSystemSleep),
            name: NSWorkspace.willSleepNotification,
            object: nil
        )
        NSWorkspace.shared.notificationCenter.addObserver(
            self,
            selector: #selector(handleSystemWake),
            name: NSWorkspace.didWakeNotification,
            object: nil
        )
    }

    @objc private func handleConfigChanged() {
        startMonitoringIfNeeded()
    }

    @objc private func handleSystemSleep() {
        stopMonitoring()
    }

    @objc private func handleSystemWake() {
        startMonitoringIfNeeded()
    }

    /// 标记 ATools 自身写入剪贴板的 changeCount，防止自身复制（如复制文件路径、偏好设置文字）自环污染
    public func markSelfGeneratedChangeCount(_ count: Int = NSPasteboard.general.changeCount) {
        ignoredChangeCounts.insert(count)
        if ignoredChangeCounts.count > 20 {
            if let minVal = ignoredChangeCounts.min() {
                ignoredChangeCounts.remove(minVal)
            }
        }
    }

    /// 根据配置按需启停轻量轮询
    public func startMonitoringIfNeeded() {
        guard ConfigManager.shared.config.autoPasteOnSummonAfterCopy else {
            stopMonitoring()
            return
        }

        guard timer == nil else { return }

        lastChangeCount = NSPasteboard.general.changeCount
        // 使用 0.5s 周期，配合 0.2s 容差 (tolerance) 允许系统合并唤醒周期，极致节能
        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.tick()
        }
        t.tolerance = 0.2
        RunLoop.main.add(t, forMode: .common)
        self.timer = t
    }

    public func stopMonitoring() {
        timer?.invalidate()
        timer = nil
    }

    private func tick() {
        let current = NSPasteboard.general.changeCount
        if current != lastChangeCount {
            lastChangeCount = current
            // 只要不是 ATools 自身产出的复制，记录最近一次外部复制时间戳
            if !ignoredChangeCounts.contains(current) {
                lastCopyTime = Date()
                runtimeLog("[PasteboardRecency] Detected copy change: \(current) at \(Date())")
            }
        }
    }

    /// 检查并提取合规的待粘贴文本，一旦获取成功立即锁定消费，杜绝重复粘贴
    public func checkAndConsumePasteContent(withinSeconds: TimeInterval = 3.0) -> String? {
        guard ConfigManager.shared.config.autoPasteOnSummonAfterCopy else { return nil }

        let pb = NSPasteboard.general
        let currentCount = pb.changeCount

        // 关键防护 1：唤醒瞬时增量比对（Instant Tick Check）！
        // 若用户在复制后极速按下快捷键（如 10ms~200ms 内），此时 0.5s 定时器尚未触发下一次 tick。
        // 在呼出瞬间主动探测，若剪贴板相较于上次已知 count 发生了新变化且不在忽略列表中，立即将其确认为“刚发生的新复制”！
        if currentCount != lastChangeCount {
            lastChangeCount = currentCount
            if !ignoredChangeCounts.contains(currentCount) {
                lastCopyTime = Date()
                runtimeLog("[PasteboardRecency] Instant catch copy change: \(currentCount)")
            }
        }

        guard let copyTime = lastCopyTime else { return nil }

        let elapsed = Date().timeIntervalSince(copyTime)
        guard elapsed >= 0 && elapsed <= withinSeconds else {
            runtimeLog("[PasteboardRecency] Copy expired: elapsed \(elapsed)s > \(withinSeconds)s")
            lastCopyTime = nil
            return nil
        }

        // 避免重复消费相同版本或 ATools 自身写入的版本
        guard currentCount != lastConsumedChangeCount else {
            runtimeLog("[PasteboardRecency] Already consumed count \(currentCount)")
            return nil
        }
        guard !ignoredChangeCounts.contains(currentCount) else {
            runtimeLog("[PasteboardRecency] Ignored self-generated count \(currentCount)")
            return nil
        }

        // 隐私与安全审查：严禁注入密码管理器保密数据
        if let types = pb.types {
            for sensitive in Self.sensitivePasteboardTypes {
                if types.contains(sensitive) {
                    markConsumed()
                    return nil
                }
            }
        }

        // 读取纯文本或访达文件路径名
        var rawText: String?
        if let str = pb.string(forType: .string), !str.isEmpty {
            rawText = str
        } else if let urls = pb.readObjects(forClasses: [NSURL.self], options: nil) as? [URL], let first = urls.first {
            rawText = first.lastPathComponent
        }

        guard let text = rawText else { return nil }

        // 清洗空白与换行符
        var sanitized = text.replacingOccurrences(of: "\r\n", with: " ")
                            .replacingOccurrences(of: "\n", with: " ")
                            .replacingOccurrences(of: "\r", with: " ")
                            .trimmingCharacters(in: .whitespacesAndNewlines)

        guard !sanitized.isEmpty else {
            markConsumed()
            return nil
        }

        // 长度截断保护（单行搜索框最多填充 300 字符，杜绝长文撑爆）
        if sanitized.count > 300 {
            sanitized = String(sanitized.prefix(300))
        }

        // 标记消费成功，注销当前版本
        markConsumed()
        return sanitized
    }

    public func markConsumed() {
        lastConsumedChangeCount = NSPasteboard.general.changeCount
        lastCopyTime = nil
    }

    /// 供单元测试与诊断套件直接模拟外部复制到达
    public func simulateExternalCopy(text: String, at time: Date = Date()) {
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(text, forType: .string)
        lastChangeCount = pb.changeCount
        lastCopyTime = time
    }
}
